/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.ConfigurationDtoInteger();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigurationDtoInteger', function() {
    it('should create an instance of ConfigurationDtoInteger', function() {
      // uncomment below and update the code to test ConfigurationDtoInteger
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be.a(Api.ConfigurationDtoInteger);
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property documentType (base name: "documentType")', function() {
      // uncomment below and update the code to test the property documentType
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property editorConfig (base name: "editorConfig")', function() {
      // uncomment below and update the code to test the property editorConfig
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property editorType (base name: "editorType")', function() {
      // uncomment below and update the code to test the property editorType
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property editorUrl (base name: "editorUrl")', function() {
      // uncomment below and update the code to test the property editorUrl
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property startFilling (base name: "startFilling")', function() {
      // uncomment below and update the code to test the property startFilling
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property fillingStatus (base name: "fillingStatus")', function() {
      // uncomment below and update the code to test the property fillingStatus
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property startFillingMode (base name: "startFillingMode")', function() {
      // uncomment below and update the code to test the property startFillingMode
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

    it('should have the property fillingSessionId (base name: "fillingSessionId")', function() {
      // uncomment below and update the code to test the property fillingSessionId
      //var instance = new Api.ConfigurationDtoInteger();
      //expect(instance).to.be();
    });

  });

}));
