/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.DocServiceUrlDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocServiceUrlDto', function() {
    it('should create an instance of DocServiceUrlDto', function() {
      // uncomment below and update the code to test DocServiceUrlDto
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be.a(Api.DocServiceUrlDto);
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServiceUrlApi (base name: "docServiceUrlApi")', function() {
      // uncomment below and update the code to test the property docServiceUrlApi
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServiceUrl (base name: "docServiceUrl")', function() {
      // uncomment below and update the code to test the property docServiceUrl
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServiceUrlInternal (base name: "docServiceUrlInternal")', function() {
      // uncomment below and update the code to test the property docServiceUrlInternal
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServicePortalUrl (base name: "docServicePortalUrl")', function() {
      // uncomment below and update the code to test the property docServicePortalUrl
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServiceSignatureHeader (base name: "docServiceSignatureHeader")', function() {
      // uncomment below and update the code to test the property docServiceSignatureHeader
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property docServiceSslVerification (base name: "docServiceSslVerification")', function() {
      // uncomment below and update the code to test the property docServiceSslVerification
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

    it('should have the property isDefault (base name: "isDefault")', function() {
      // uncomment below and update the code to test the property isDefault
      //var instance = new Api.DocServiceUrlDto();
      //expect(instance).to.be();
    });

  });

}));
