/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.RoomFromTemplateStatusDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RoomFromTemplateStatusDto', function() {
    it('should create an instance of RoomFromTemplateStatusDto', function() {
      // uncomment below and update the code to test RoomFromTemplateStatusDto
      //var instance = new Api.RoomFromTemplateStatusDto();
      //expect(instance).to.be.a(Api.RoomFromTemplateStatusDto);
    });

    it('should have the property roomId (base name: "roomId")', function() {
      // uncomment below and update the code to test the property roomId
      //var instance = new Api.RoomFromTemplateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instance = new Api.RoomFromTemplateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new Api.RoomFromTemplateStatusDto();
      //expect(instance).to.be();
    });

    it('should have the property isCompleted (base name: "isCompleted")', function() {
      // uncomment below and update the code to test the property isCompleted
      //var instance = new Api.RoomFromTemplateStatusDto();
      //expect(instance).to.be();
    });

  });

}));
