/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.UpdateWebhooksConfigRequestsDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateWebhooksConfigRequestsDto', function() {
    it('should create an instance of UpdateWebhooksConfigRequestsDto', function() {
      // uncomment below and update the code to test UpdateWebhooksConfigRequestsDto
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be.a(Api.UpdateWebhooksConfigRequestsDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property uri (base name: "uri")', function() {
      // uncomment below and update the code to test the property uri
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property secretKey (base name: "secretKey")', function() {
      // uncomment below and update the code to test the property secretKey
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property ssl (base name: "ssl")', function() {
      // uncomment below and update the code to test the property ssl
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property triggers (base name: "triggers")', function() {
      // uncomment below and update the code to test the property triggers
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property targetId (base name: "targetId")', function() {
      // uncomment below and update the code to test the property targetId
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Api.UpdateWebhooksConfigRequestsDto();
      //expect(instance).to.be();
    });

  });

}));
