/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ConfirmType.
* @enum {}
* @readonly
*/
export default class ConfirmType {
    
        /**
         * value: 0
         * @const
         */
        "EmpInvite" = 0;

    
        /**
         * value: 1
         * @const
         */
        "LinkInvite" = 1;

    
        /**
         * value: 2
         * @const
         */
        "PortalSuspend" = 2;

    
        /**
         * value: 3
         * @const
         */
        "PortalContinue" = 3;

    
        /**
         * value: 4
         * @const
         */
        "PortalRemove" = 4;

    
        /**
         * value: 5
         * @const
         */
        "DnsChange" = 5;

    
        /**
         * value: 6
         * @const
         */
        "PortalOwnerChange" = 6;

    
        /**
         * value: 7
         * @const
         */
        "Activation" = 7;

    
        /**
         * value: 8
         * @const
         */
        "EmailChange" = 8;

    
        /**
         * value: 9
         * @const
         */
        "EmailActivation" = 9;

    
        /**
         * value: 10
         * @const
         */
        "PasswordChange" = 10;

    
        /**
         * value: 11
         * @const
         */
        "ProfileRemove" = 11;

    
        /**
         * value: 12
         * @const
         */
        "PhoneActivation" = 12;

    
        /**
         * value: 13
         * @const
         */
        "PhoneAuth" = 13;

    
        /**
         * value: 14
         * @const
         */
        "Auth" = 14;

    
        /**
         * value: 15
         * @const
         */
        "TfaActivation" = 15;

    
        /**
         * value: 16
         * @const
         */
        "TfaAuth" = 16;

    
        /**
         * value: 17
         * @const
         */
        "Wizard" = 17;

    
        /**
         * value: 18
         * @const
         */
        "GuestShareLink" = 18;

    

    /**
    * Returns a <code>ConfirmType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/ConfirmType} The enum <code>ConfirmType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

