/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomFilterParameters model module.
 * @module models/CustomFilterParameters
 * @version 3.2.0
 */
class CustomFilterParameters {
    /**
     * Constructs a new <code>CustomFilterParameters</code>.
     * The parameters for setting the Custom Filter editing mode.
     * @alias module:models/CustomFilterParameters
     */
    constructor() { 
        
        CustomFilterParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFilterParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/CustomFilterParameters} obj Optional instance to populate.
     * @return {module:models/CustomFilterParameters} The populated <code>CustomFilterParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFilterParameters();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomFilterParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomFilterParameters</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Specifies whether the Custom Filter editing mode is enabled or not.
 * @member {Boolean} enabled
 */
CustomFilterParameters.prototype['enabled'] = undefined;






export default CustomFilterParameters;

