/**
 *
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
import ApiClient from '../ApiClient';
import ApiDateTime from './ApiDateTime';
import EditHistoryAuthor from './EditHistoryAuthor';

/**
 * The EditHistoryChangesWrapper model module.
 * @module models/EditHistoryChangesWrapper
 * @version 3.2.0
 */
class EditHistoryChangesWrapper {
    /**
     * Constructs a new <code>EditHistoryChangesWrapper</code>.
     * The parameters of the file editing history.
     * @alias module:models/EditHistoryChangesWrapper
     */
    constructor() { 
        
        EditHistoryChangesWrapper.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditHistoryChangesWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/EditHistoryChangesWrapper} obj Optional instance to populate.
     * @return {module:models/EditHistoryChangesWrapper} The populated <code>EditHistoryChangesWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditHistoryChangesWrapper();

            if (data.hasOwnProperty('user')) {
                obj['user'] = EditHistoryAuthor.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiDateTime.constructFromObject(data['created']);
            }
            if (data.hasOwnProperty('documentSha256')) {
                obj['documentSha256'] = ApiClient.convertToType(data['documentSha256'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditHistoryChangesWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditHistoryChangesWrapper</code>.
     */
    static validateJSON(data) {
        // validate the optional field `user`
        if (data['user']) { // data not null
          EditHistoryAuthor.validateJSON(data['user']);
        }
        // validate the optional field `created`
        if (data['created']) { // data not null
          ApiDateTime.validateJSON(data['created']);
        }
        // ensure the json data is a string
        if (data['documentSha256'] && !(typeof data['documentSha256'] === 'string' || data['documentSha256'] instanceof String)) {
            throw new Error("Expected the field `documentSha256` to be a primitive type in the JSON string but got " + data['documentSha256']);
        }

        return true;
    }


}



/**
 * @member {module:models/EditHistoryAuthor} user
 */
EditHistoryChangesWrapper.prototype['user'] = undefined;

/**
 * @member {module:models/ApiDateTime} created
 */
EditHistoryChangesWrapper.prototype['created'] = undefined;

/**
 * The document hash generated by the SHA-256 algorithm.
 * @member {String} documentSha256
 */
EditHistoryChangesWrapper.prototype['documentSha256'] = undefined;






export default EditHistoryChangesWrapper;

