/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EditorType.
* @enum {}
* @readonly
*/
export default class EditorType {
    
        /**
         * value: 0
         * @const
         */
        "Desktop" = 0;

    
        /**
         * value: 1
         * @const
         */
        "Mobile" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Embedded" = 2;

    

    /**
    * Returns a <code>EditorType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/EditorType} The enum <code>EditorType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

