// (c) Copyright Ascensio System SIA 2009-2025
// 
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
// 
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
// 
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
// 
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
// 
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
// 
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
import ApiClient from '../ApiClient';
import ApiDateTime from './ApiDateTime';
import EditHistoryAuthor from './EditHistoryAuthor';

/**
 * The EditHistoryChangesWrapper model module.
 * @module models/EditHistoryChangesWrapper
 * @version 3.2.0
 */
class EditHistoryChangesWrapper {
    /**
     * Constructs a new <code>EditHistoryChangesWrapper</code>.
     * The parameters of the file editing history.
     * @alias module:models/EditHistoryChangesWrapper
     */
    constructor() { 
        
        EditHistoryChangesWrapper.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditHistoryChangesWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/EditHistoryChangesWrapper} obj Optional instance to populate.
     * @return {module:models/EditHistoryChangesWrapper} The populated <code>EditHistoryChangesWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditHistoryChangesWrapper();

            if (data.hasOwnProperty('user')) {
                obj['user'] = EditHistoryAuthor.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiDateTime.constructFromObject(data['created']);
            }
            if (data.hasOwnProperty('documentSha256')) {
                obj['documentSha256'] = ApiClient.convertToType(data['documentSha256'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditHistoryChangesWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditHistoryChangesWrapper</code>.
     */
    static validateJSON(data) {
        // validate the optional field `user`
        if (data['user']) { // data not null
          EditHistoryAuthor.validateJSON(data['user']);
        }
        // validate the optional field `created`
        if (data['created']) { // data not null
          ApiDateTime.validateJSON(data['created']);
        }
        // ensure the json data is a string
        if (data['documentSha256'] && !(typeof data['documentSha256'] === 'string' || data['documentSha256'] instanceof String)) {
            throw new Error("Expected the field `documentSha256` to be a primitive type in the JSON string but got " + data['documentSha256']);
        }

        return true;
    }


}



/**
 * @member {module:models/EditHistoryAuthor} user
 */
EditHistoryChangesWrapper.prototype['user'] = undefined;

/**
 * @member {module:models/ApiDateTime} created
 */
EditHistoryChangesWrapper.prototype['created'] = undefined;

/**
 * The document hash generated by the SHA-256 algorithm.
 * @member {String} documentSha256
 */
EditHistoryChangesWrapper.prototype['documentSha256'] = undefined;






export default EditHistoryChangesWrapper;

