/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActiveConnectionsWrapperLinksInner from './ActiveConnectionsWrapperLinksInner';
import FilesStatisticsResultDto from './FilesStatisticsResultDto';

/**
 * The FilesStatisticsResultWrapper model module.
 * @module models/FilesStatisticsResultWrapper
 * @version 3.2.0
 */
class FilesStatisticsResultWrapper {
    /**
     * Constructs a new <code>FilesStatisticsResultWrapper</code>.
     * @alias module:models/FilesStatisticsResultWrapper
     */
    constructor() { 
        
        FilesStatisticsResultWrapper.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilesStatisticsResultWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/FilesStatisticsResultWrapper} obj Optional instance to populate.
     * @return {module:models/FilesStatisticsResultWrapper} The populated <code>FilesStatisticsResultWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilesStatisticsResultWrapper();

            if (data.hasOwnProperty('response')) {
                obj['response'] = FilesStatisticsResultDto.constructFromObject(data['response']);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [ActiveConnectionsWrapperLinksInner]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FilesStatisticsResultWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FilesStatisticsResultWrapper</code>.
     */
    static validateJSON(data) {
        // validate the optional field `response`
        if (data['response']) { // data not null
          FilesStatisticsResultDto.validateJSON(data['response']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                ActiveConnectionsWrapperLinksInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:models/FilesStatisticsResultDto} response
 */
FilesStatisticsResultWrapper.prototype['response'] = undefined;

/**
 * @member {Number} count
 */
FilesStatisticsResultWrapper.prototype['count'] = undefined;

/**
 * @member {Array.<module:models/ActiveConnectionsWrapperLinksInner>} links
 */
FilesStatisticsResultWrapper.prototype['links'] = undefined;

/**
 * @member {Number} status
 */
FilesStatisticsResultWrapper.prototype['status'] = undefined;

/**
 * @member {Number} statusCode
 */
FilesStatisticsResultWrapper.prototype['statusCode'] = undefined;






export default FilesStatisticsResultWrapper;

