/**
 *
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FileReferenceData model module.
 * @module models/FileReferenceData
 * @version 3.2.0
 */
class FileReferenceData {
    /**
     * Constructs a new <code>FileReferenceData</code>.
     * An object that is generated by the integrator to uniquely identify a file in its system.
     * @alias module:models/FileReferenceData
     */
    constructor() { 
        
        FileReferenceData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FileReferenceData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/FileReferenceData} obj Optional instance to populate.
     * @return {module:models/FileReferenceData} The populated <code>FileReferenceData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileReferenceData();

            if (data.hasOwnProperty('fileKey')) {
                obj['fileKey'] = ApiClient.convertToType(data['fileKey'], 'String');
            }
            if (data.hasOwnProperty('instanceId')) {
                obj['instanceId'] = ApiClient.convertToType(data['instanceId'], 'String');
            }
            if (data.hasOwnProperty('roomId')) {
                obj['roomId'] = ApiClient.convertToType(data['roomId'], 'String');
            }
            if (data.hasOwnProperty('canEditRoom')) {
                obj['canEditRoom'] = ApiClient.convertToType(data['canEditRoom'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FileReferenceData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FileReferenceData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fileKey'] && !(typeof data['fileKey'] === 'string' || data['fileKey'] instanceof String)) {
            throw new Error("Expected the field `fileKey` to be a primitive type in the JSON string but got " + data['fileKey']);
        }
        // ensure the json data is a string
        if (data['instanceId'] && !(typeof data['instanceId'] === 'string' || data['instanceId'] instanceof String)) {
            throw new Error("Expected the field `instanceId` to be a primitive type in the JSON string but got " + data['instanceId']);
        }
        // ensure the json data is a string
        if (data['roomId'] && !(typeof data['roomId'] === 'string' || data['roomId'] instanceof String)) {
            throw new Error("Expected the field `roomId` to be a primitive type in the JSON string but got " + data['roomId']);
        }

        return true;
    }


}



/**
 * The unique document identifier used by the service to get a link to the file.
 * @member {String} fileKey
 */
FileReferenceData.prototype['fileKey'] = undefined;

/**
 * The unique system identifier.
 * @member {String} instanceId
 */
FileReferenceData.prototype['instanceId'] = undefined;

/**
 * Room ID
 * @member {String} roomId
 */
FileReferenceData.prototype['roomId'] = undefined;

/**
 * Specifies if the room can be edited out or not.
 * @member {Boolean} canEditRoom
 */
FileReferenceData.prototype['canEditRoom'] = undefined;






export default FileReferenceData;

