/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FileOperationType.
* @enum {}
* @readonly
*/
export default class FileOperationType {
    
        /**
         * value: 0
         * @const
         */
        "Move" = 0;

    
        /**
         * value: 1
         * @const
         */
        "Copy" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Delete" = 2;

    
        /**
         * value: 3
         * @const
         */
        "Download" = 3;

    
        /**
         * value: 4
         * @const
         */
        "MarkAsRead" = 4;

    
        /**
         * value: 5
         * @const
         */
        "Import" = 5;

    
        /**
         * value: 6
         * @const
         */
        "Convert" = 6;

    
        /**
         * value: 7
         * @const
         */
        "Duplicate" = 7;

    

    /**
    * Returns a <code>FileOperationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/FileOperationType} The enum <code>FileOperationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

