/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FileShare.
* @enum {}
* @readonly
*/
export default class FileShare {
    
        /**
         * value: 0
         * @const
         */
        "None" = 0;

    
        /**
         * value: 1
         * @const
         */
        "ReadWrite" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Read" = 2;

    
        /**
         * value: 3
         * @const
         */
        "Restrict" = 3;

    
        /**
         * value: 4
         * @const
         */
        "Varies" = 4;

    
        /**
         * value: 5
         * @const
         */
        "Review" = 5;

    
        /**
         * value: 6
         * @const
         */
        "Comment" = 6;

    
        /**
         * value: 7
         * @const
         */
        "FillForms" = 7;

    
        /**
         * value: 8
         * @const
         */
        "CustomFilter" = 8;

    
        /**
         * value: 9
         * @const
         */
        "RoomManager" = 9;

    
        /**
         * value: 10
         * @const
         */
        "Editing" = 10;

    
        /**
         * value: 11
         * @const
         */
        "ContentCreator" = 11;

    

    /**
    * Returns a <code>FileShare</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/FileShare} The enum <code>FileShare</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

