/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class NotificationType.
* @enum {}
* @readonly
*/
export default class NotificationType {
    
        /**
         * value: 0
         * @const
         */
        "Badges" = 0;

    
        /**
         * value: 1
         * @const
         */
        "RoomsActivity" = 1;

    
        /**
         * value: 2
         * @const
         */
        "DailyFeed" = 2;

    
        /**
         * value: 3
         * @const
         */
        "UsefullTips" = 3;

    

    /**
    * Returns a <code>NotificationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/NotificationType} The enum <code>NotificationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

