/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentUrlRequestsDto model module.
 * @module models/PaymentUrlRequestsDto
 * @version 3.2.0
 */
class PaymentUrlRequestsDto {
    /**
     * Constructs a new <code>PaymentUrlRequestsDto</code>.
     * The request parameters for the payment URL configuration with quantity information.
     * @alias module:models/PaymentUrlRequestsDto
     */
    constructor() { 
        
        PaymentUrlRequestsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentUrlRequestsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/PaymentUrlRequestsDto} obj Optional instance to populate.
     * @return {module:models/PaymentUrlRequestsDto} The populated <code>PaymentUrlRequestsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentUrlRequestsDto();

            if (data.hasOwnProperty('backUrl')) {
                obj['backUrl'] = ApiClient.convertToType(data['backUrl'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], {'String': 'Number'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentUrlRequestsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentUrlRequestsDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['backUrl'] && !(typeof data['backUrl'] === 'string' || data['backUrl'] instanceof String)) {
            throw new Error("Expected the field `backUrl` to be a primitive type in the JSON string but got " + data['backUrl']);
        }

        return true;
    }


}



/**
 * The URL where the user will be redirected after payment processing.
 * @member {String} backUrl
 */
PaymentUrlRequestsDto.prototype['backUrl'] = undefined;

/**
 * The quantity of payment
 * @member {Object.<String, Number>} quantity
 */
PaymentUrlRequestsDto.prototype['quantity'] = undefined;






export default PaymentUrlRequestsDto;

