/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SettingsRequestDto model module.
 * @module models/SettingsRequestDto
 * @version 3.2.0
 */
class SettingsRequestDto {
    /**
     * Constructs a new <code>SettingsRequestDto</code>.
     * The settings request parameters.
     * @alias module:models/SettingsRequestDto
     */
    constructor() { 
        
        SettingsRequestDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettingsRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/SettingsRequestDto} obj Optional instance to populate.
     * @return {module:models/SettingsRequestDto} The populated <code>SettingsRequestDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettingsRequestDto();

            if (data.hasOwnProperty('set')) {
                obj['set'] = ApiClient.convertToType(data['set'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SettingsRequestDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SettingsRequestDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Specifies whether to set the specified settings or not.
 * @member {Boolean} set
 */
SettingsRequestDto.prototype['set'] = undefined;






export default SettingsRequestDto;

