/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SortedByType.
* @enum {}
* @readonly
*/
export default class SortedByType {
    
        /**
         * value: 0
         * @const
         */
        "DateAndTime" = 0;

    
        /**
         * value: 1
         * @const
         */
        "AZ" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Size" = 2;

    
        /**
         * value: 3
         * @const
         */
        "Author" = 3;

    
        /**
         * value: 4
         * @const
         */
        "Type" = 4;

    
        /**
         * value: 5
         * @const
         */
        "New" = 5;

    
        /**
         * value: 6
         * @const
         */
        "DateAndTimeCreation" = 6;

    
        /**
         * value: 7
         * @const
         */
        "RoomType" = 7;

    
        /**
         * value: 8
         * @const
         */
        "Tags" = 8;

    
        /**
         * value: 9
         * @const
         */
        "Room" = 9;

    
        /**
         * value: 10
         * @const
         */
        "CustomOrder" = 10;

    
        /**
         * value: 11
         * @const
         */
        "LastOpened" = 11;

    
        /**
         * value: 12
         * @const
         */
        "UsedSpace" = 12;

    

    /**
    * Returns a <code>SortedByType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/SortedByType} The enum <code>SortedByType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

