/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status.
* @enum {}
* @readonly
*/
export default class Status {
    
        /**
         * value: 0
         * @const
         */
        "Ok" = 0;

    
        /**
         * value: 1
         * @const
         */
        "Invalid" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Expired" = 2;

    
        /**
         * value: 3
         * @const
         */
        "RequiredPassword" = 3;

    
        /**
         * value: 4
         * @const
         */
        "InvalidPassword" = 4;

    
        /**
         * value: 5
         * @const
         */
        "ExternalAccessDenied" = 5;

    

    /**
    * Returns a <code>Status</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/Status} The enum <code>Status</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

