/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StorageEncryptionRequestsDto model module.
 * @module models/StorageEncryptionRequestsDto
 * @version 3.2.0
 */
class StorageEncryptionRequestsDto {
    /**
     * Constructs a new <code>StorageEncryptionRequestsDto</code>.
     * The request parameters for managing storage encryption operations and notifications.
     * @alias module:models/StorageEncryptionRequestsDto
     */
    constructor() { 
        
        StorageEncryptionRequestsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageEncryptionRequestsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/StorageEncryptionRequestsDto} obj Optional instance to populate.
     * @return {module:models/StorageEncryptionRequestsDto} The populated <code>StorageEncryptionRequestsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageEncryptionRequestsDto();

            if (data.hasOwnProperty('notifyUsers')) {
                obj['notifyUsers'] = ApiClient.convertToType(data['notifyUsers'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageEncryptionRequestsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageEncryptionRequestsDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Specifies whether the users receive notifications about the storage encryption operations.
 * @member {Boolean} notifyUsers
 */
StorageEncryptionRequestsDto.prototype['notifyUsers'] = undefined;






export default StorageEncryptionRequestsDto;

