/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeepLinkHandlingMode from './DeepLinkHandlingMode';

/**
 * The TenantDeepLinkSettings model module.
 * @module models/TenantDeepLinkSettings
 * @version 3.2.0
 */
class TenantDeepLinkSettings {
    /**
     * Constructs a new <code>TenantDeepLinkSettings</code>.
     * The deep link settings.
     * @alias module:models/TenantDeepLinkSettings
     */
    constructor() { 
        
        TenantDeepLinkSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TenantDeepLinkSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TenantDeepLinkSettings} obj Optional instance to populate.
     * @return {module:models/TenantDeepLinkSettings} The populated <code>TenantDeepLinkSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TenantDeepLinkSettings();

            if (data.hasOwnProperty('handlingMode')) {
                obj['handlingMode'] = DeepLinkHandlingMode.constructFromObject(data['handlingMode']);
            }
            if (data.hasOwnProperty('lastModified')) {
                obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TenantDeepLinkSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TenantDeepLinkSettings</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:models/DeepLinkHandlingMode} handlingMode
 */
TenantDeepLinkSettings.prototype['handlingMode'] = undefined;

/**
 * @member {Date} lastModified
 */
TenantDeepLinkSettings.prototype['lastModified'] = undefined;






export default TenantDeepLinkSettings;

