/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TenantWalletSettings model module.
 * @module models/TenantWalletSettings
 * @version 3.2.0
 */
class TenantWalletSettings {
    /**
     * Constructs a new <code>TenantWalletSettings</code>.
     * @alias module:models/TenantWalletSettings
     */
    constructor() { 
        
        TenantWalletSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TenantWalletSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/TenantWalletSettings} obj Optional instance to populate.
     * @return {module:models/TenantWalletSettings} The populated <code>TenantWalletSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TenantWalletSettings();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('minBalance')) {
                obj['minBalance'] = ApiClient.convertToType(data['minBalance'], 'Number');
            }
            if (data.hasOwnProperty('upToBalance')) {
                obj['upToBalance'] = ApiClient.convertToType(data['upToBalance'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('lastModified')) {
                obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TenantWalletSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TenantWalletSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}



/**
 * Enabled
 * @member {Boolean} enabled
 */
TenantWalletSettings.prototype['enabled'] = undefined;

/**
 * Minimun balance
 * @member {Number} minBalance
 */
TenantWalletSettings.prototype['minBalance'] = undefined;

/**
 * Up to balance
 * @member {Number} upToBalance
 */
TenantWalletSettings.prototype['upToBalance'] = undefined;

/**
 * Currency
 * @member {String} currency
 */
TenantWalletSettings.prototype['currency'] = undefined;

/**
 * @member {Date} lastModified
 */
TenantWalletSettings.prototype['lastModified'] = undefined;






export default TenantWalletSettings;

