/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseBatchRequestDtoFolderIdsInner from './BaseBatchRequestDtoFolderIdsInner';

/**
 * The UpdateRoomsQuotaRequestDtoInteger model module.
 * @module models/UpdateRoomsQuotaRequestDtoInteger
 * @version 3.2.0
 */
class UpdateRoomsQuotaRequestDtoInteger {
    /**
     * Constructs a new <code>UpdateRoomsQuotaRequestDtoInteger</code>.
     * The request parameters for updating the room quota.
     * @alias module:models/UpdateRoomsQuotaRequestDtoInteger
     */
    constructor() { 
        
        UpdateRoomsQuotaRequestDtoInteger.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateRoomsQuotaRequestDtoInteger</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UpdateRoomsQuotaRequestDtoInteger} obj Optional instance to populate.
     * @return {module:models/UpdateRoomsQuotaRequestDtoInteger} The populated <code>UpdateRoomsQuotaRequestDtoInteger</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRoomsQuotaRequestDtoInteger();

            if (data.hasOwnProperty('roomIds')) {
                obj['roomIds'] = ApiClient.convertToType(data['roomIds'], [BaseBatchRequestDtoFolderIdsInner]);
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateRoomsQuotaRequestDtoInteger</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateRoomsQuotaRequestDtoInteger</code>.
     */
    static validateJSON(data) {
        if (data['roomIds']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['roomIds'])) {
                throw new Error("Expected the field `roomIds` to be an array in the JSON data but got " + data['roomIds']);
            }
            // validate the optional field `roomIds` (array)
            for (const item of data['roomIds']) {
                BaseBatchRequestDtoFolderIdsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The list of room IDs.
 * @member {Array.<module:models/BaseBatchRequestDtoFolderIdsInner>} roomIds
 */
UpdateRoomsQuotaRequestDtoInteger.prototype['roomIds'] = undefined;

/**
 * The room quota.
 * @member {Number} quota
 */
UpdateRoomsQuotaRequestDtoInteger.prototype['quota'] = undefined;






export default UpdateRoomsQuotaRequestDtoInteger;

