/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WebhookGroupStatus.
* @enum {}
* @readonly
*/
export default class WebhookGroupStatus {
    
        /**
         * value: 0
         * @const
         */
        "None" = 0;

    
        /**
         * value: 1
         * @const
         */
        "NotSent" = 1;

    
        /**
         * value: 2
         * @const
         */
        "Status2xx" = 2;

    
        /**
         * value: 4
         * @const
         */
        "Status3xx" = 4;

    
        /**
         * value: 8
         * @const
         */
        "Status4xx" = 8;

    
        /**
         * value: 16
         * @const
         */
        "Status5xx" = 16;

    

    /**
    * Returns a <code>WebhookGroupStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/WebhookGroupStatus} The enum <code>WebhookGroupStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

