/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.SettingsTFASettingsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SettingsTFASettingsApi', function() {
    describe('getTfaAppCodes', function() {
      it('should call getTfaAppCodes successfully', function(done) {
        //uncomment below and update the code to test getTfaAppCodes
        //instance.getTfaAppCodes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTfaConfirmUrl', function() {
      it('should call getTfaConfirmUrl successfully', function(done) {
        //uncomment below and update the code to test getTfaConfirmUrl
        //instance.getTfaConfirmUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTfaSettings', function() {
      it('should call getTfaSettings successfully', function(done) {
        //uncomment below and update the code to test getTfaSettings
        //instance.getTfaSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tfaAppGenerateSetupCode', function() {
      it('should call tfaAppGenerateSetupCode successfully', function(done) {
        //uncomment below and update the code to test tfaAppGenerateSetupCode
        //instance.tfaAppGenerateSetupCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tfaValidateAuthCode', function() {
      it('should call tfaValidateAuthCode successfully', function(done) {
        //uncomment below and update the code to test tfaValidateAuthCode
        //instance.tfaValidateAuthCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unlinkTfaApp', function() {
      it('should call unlinkTfaApp successfully', function(done) {
        //uncomment below and update the code to test unlinkTfaApp
        //instance.unlinkTfaApp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTfaAppCodes', function() {
      it('should call updateTfaAppCodes successfully', function(done) {
        //uncomment below and update the code to test updateTfaAppCodes
        //instance.updateTfaAppCodes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTfaSettings', function() {
      it('should call updateTfaSettings successfully', function(done) {
        //uncomment below and update the code to test updateTfaSettings
        //instance.updateTfaSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTfaSettingsLink', function() {
      it('should call updateTfaSettingsLink successfully', function(done) {
        //uncomment below and update the code to test updateTfaSettingsLink
        //instance.updateTfaSettingsLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
